name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit
jobs:
  unit-tests:
    name: Unit Tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Unit Tests
      run: npx playwright test tests/unit/ --reporter=allure-playwright
    - name: Generate Allure Report for Unit Tests
      if: always()
      run: |
        npm install -g allure-commandline
        allure generate allure-results --clean -o allure-report-unit
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: unit-test-report
        path: playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: unit-allure-report
        path: allure-report-unit/
        retention-days: 30
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: unit-allure-results
        path: allure-results/
        retention-days: 30

  integration-tests:
    name: Integration Tests
    needs: unit-tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Integration Tests
      run: |
        npx playwright test --project=${{ github.event.inputs.browser || 'chromium' }} \
        --grep-invert @unit --reporter=allure-playwright
    - name: Generate Allure Report for Integration Tests
      if: always()
      run: |
        npm install -g allure-commandline
        allure generate allure-results --clean -o allure-report-integration
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-test-report
        path: playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-allure-report
        path: allure-report-integration/
        retention-days: 30
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-allure-results
        path: allure-results/
        retention-days: 30
